### ISSUE TITLE
Question: Why are you using `HttpContext.Session` to store the options in the Demo project?

### ISSUE THREAD

**Issue by poveilleux** [abergs/fido2-net-lib#144]
Hi,

I was wondering why you are using `HttpContext.Session` to store the options (either Make Credential or Assertion). Is it only to prevent round-tripping the options between the client and the server or there are security reasons for this? I am implementing my FIDO2 server based on the Demo you are providing and I was thinking of ditching the use of Session.

Thank you

**Comment by abergs** [comment]
You really need to keep the options (at least the challenge) server-side since otherwise you can't verify that the client signed the random challenge you created by you. However, you don't have to use a session,anything serverside that's connected to those options (db/redis/in-mem cache whatever suits you)

**Comment by poveilleux** [comment]
@abergs Excellent, it is really about the storing the challenge between generating it on the options endpoint and asserting it was successful on the assertion endpoint. Thank you for the quick response!
