### ISSUE TITLE
Request for new nuget release with recent PRs

### ISSUE THREAD

**Issue by mackie1001** [abergs/fido2-net-lib#167]
I'm in the middle of a 3.1 upgrade project and would like to upgrade all packages to latest. Is it possible to get a new nuget release some time soon please?

**Comment by abergs** [comment]
Yes @mackie1001, we should be able to release a new version. I could certainly release a preview package if that would help you get things moving?

I'm facing a problem with releasing new versions that I want to tackle, and I welcome all advise and help.

The problem is simply popularity. The project has matured, people are using the library (which is great!) which now means the releases needs to be properly managed. SemVer, Release Notes etc.

I don't have the resources to put together proper Release Notes, so I would like to automate and crowd source as much as possible. This would also help future proof the process, so that I'm not the only one at the wheel.

If anyone are able to lend their hand, please look into #149

**Comment by abergs** [comment]
@mackie1001 See: https://github.com/abergs/fido2-net-lib/pull/175

**Comment by mackie1001** [comment]
Nice work, thanks.
