### ISSUE TITLE
Client-side wasm blazor?

### ISSUE THREAD

**Issue by 0xF6** [abergs/fido2-net-lib#199]
Do you plan to develop in this direction?
[blazor security](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/?view=aspnetcore-5.0)

**Comment by abergs** [comment]
Blazor apps can easily use the library as is, I know because I've implemented one. It does of course require you to run FIDO2 on the server.

However, note that WebAuthn is a browser API. So the blazor part would only be a thin layer connecting JS to a blazor httpclient that forwards data to the backend.

So, there is nothing special with Blazor and FIDO2.
